### ISSUE TITLE
System.Fabric.FabricNotReadableException when using ServiceFabricPersistence for Outbox

### ISSUE THREAD

**Issue by dmossberg** [Particular/NServiceBus.Persistence.ServiceFabric#77]
## Problem
I'm trying to configure an endpoint to use Service Fabric persistence for Outbox. I'm using Service Fabric persistence for Sagas for the same endpoint. 

```cs
var sagaPersistence = endpointConfiguration.UsePersistence<ServiceFabricPersistence, StorageType.Sagas>();

var sagaSettings = sagaPersistence.SagaSettings();
sagaSettings.JsonSettings(new JsonSerializerSettings
{
    TypeNameHandling = TypeNameHandling.Auto,
    Converters = { new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.RoundtripKind } }
});

sagaPersistence.StateManager(stateManager);

// This part seems to cause the exception:  
var outboxPersistence = endpointConfiguration.UsePersistence<ServiceFabricPersistence, StorageType.Outbox>();
outboxPersistence.StateManager(stateManager);

endpointConfiguration.EnableOutbox();
```

Only when I enable Outbox I get the following exception. The code above works fine if I skip the Outbox part, i.e only configure the Saga persistence for Service Fabric. 

```
System.Fabric.FabricNotReadableException
  HResult=0x80071C7C
  Message=State Manager is currently not readable.
  Source=Microsoft.ServiceFabric.Data.Impl
  StackTrace:
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.ThrowIfNotReadable()
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.TryGetStateProvider(Uri stateProviderName)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.<GetOrAddStateProviderAsync>d__111`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Data.ReliableStateManagerImpl.<Microsoft-ServiceFabric-Data-IReliableStateManager-GetOrAddAsync>d__23`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Data.ReliableStateManagerImpl.<Microsoft-ServiceFabric-Data-IReliableStateManager-GetOrAddAsync>d__25`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Persistence.ServiceFabric.OutboxStateManagerExtensions.<RegisterOutboxStorage>d__0.MoveNext()
   ...
```

Any ideas?

Thanks, 
Daniel

**Comment by yvesgoeleven** [comment]
@dmossberg how are you integrating the endpoint into the service fabric host? Using a communication listener, in the main entry point or in the service?

The statemanager is not always available, it's only available on the primary replica after the state manager has been started. So the only reliable way to plug it into the config is using a communication listener.

Could that be it?

**Comment by dmossberg** [comment]
@yvesgoeleven good catch, I'm integrating the endpoint in the service (as described in https://docs.particular.net/samples/web/send-from-aspnetcore-webapi). I will check if this issue reproduces using a communication listener instead.

**Comment by yvesgoeleven** [comment]
@dmossberg that sample is integrating in the service because web api's are recommended to be stateless. But for statefull it's recommended to use the communication listener approach

**Comment by dmossberg** [comment]
@yvesgoeleven integrating the endpoint using the communication listener seems to have solved the problem, thanks for  your input and for your quick responses.

**Comment by dmossberg** [comment]
@yvesgoeleven integrating the endpoint using the communication listener solved the issue, thanks for your input and your quick response.
